### ISSUE TITLE
Properties menu disappears

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#109]
http://youtu.be/WZ7d-PS9VI0?t=12s

As seen at 0:12 the properties menu disappears from time to time... 
(& I didn't shout at it to scare it off or anything...)

also, I think the initial walkthrough needs more info, as some things I'm finding counter intuative

**Comment by ashcairo** [comment]
Thanks Alex. This should be now fixed.

If you have any suggestions for solving the counter intuition, let me know.
