### ISSUE TITLE
Titles on Tabs

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#151]
It would be really useful to have the app name on the tab, and showing when it's in editor - e.g. `*CraftWorlds: UIStart` ( \* in front to show when truncated ) vs CraftWorlds for the running app.  

<img width="1056" alt="screenshot 2015-09-05 09 37 48" src="https://cloud.githubusercontent.com/assets/7974754/9698521/f058d86a-53b1-11e5-8f8a-52d11d7def6a.png">

**Insight into how I'm working:**
One of the established games in editor, to look at how it functions
A test game to experiment with changes
The main game I'm working on
Running games to test

It would be beneficial on the website too, for SEO...
`<title>Playir: Tutorials</title>`

**Comment by ashcairo** [comment]
Thanks for this suggestion, will be online later today.

**Comment by aliekiddo** [comment]
Excellent :smile: 

I suggested \* so you could see more of the app name being edited lol - but I see "Playir: " works as a catch-all for the editor when it's not editing any app in particular too

![Doge](https://i.imgflip.com/qnb9c.jpg)
