### ISSUE TITLE
Failed to upload processed fbx

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#170]
When adding animation takes to model, with previously uploaded models

<img width="765" alt="screenshot 2015-09-23 20 22 32" src="https://cloud.githubusercontent.com/assets/7974754/10055941/e936bc7c-6230-11e5-9a8b-3d7647234579.png">

**Comment by aliekiddo** [comment]
Can anything be done about this?

**Comment by ashcairo** [comment]
Any chance of letting me know the model of you're trying to mod and what actions you're taking? A screen cast may be useful for me to reproduce and fix this.

**Comment by aliekiddo** [comment]
![2015-10-07 19_56_21](https://cloud.githubusercontent.com/assets/7974754/10347826/aa0f81ac-6d2d-11e5-8ac0-902f6eea58cd.gif)

I'm adding $model.2895 as an animation take to $model.2579 
but previously had issues when uploading $model.2895.  The same files I sent you a while ago.

**Comment by aliekiddo** [comment]
also adding $model.1976 and $model.1777 as an animation take to $model.2579

and name changes to animation takes aren't saving - e.g. $model.1788 / $model.1777 - I don't get the failed to upload for these, but I do with model.682 / $model.2579

**Comment by ashcairo** [comment]
General fix going in with https://github.com/playir/playir/issues/195
