### ISSUE TITLE
Android app ID - invalid name warning / info

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#171]
<img width="778" alt="screenshot 2015-09-26 12 08 50" src="https://cloud.githubusercontent.com/assets/7974754/10117241/70d0d2b8-6447-11e5-95fa-5ccab4cc6f83.png">

Some trouble I had creating an app ID under com.3Der... as was being replaced by com.ader... , but found this:

http://developer.android.com/guide/topics/manifest/manifest-element.html

"A full Java-language-style package name for the application. The name should be unique. The name may contain uppercase or lowercase letters ('A' through 'Z'), numbers, and underscores ('_'). However, individual package name parts may only start with letters."

Just thought it would be useful info for documentation; an error message when you try to start with an invalid character, or info on a help button

**Comment by ashcairo** [comment]
Added messages when replacing android app id. Link to developer.android.com next.

**Comment by aliekiddo** [comment]
I mentioned it in https://github.com/playir/playir/issues/140
a "?" help button may be useful next to some of the items - to display a tooltip with an explanation of what things are & formatting requirements etc...

**Comment by ashcairo** [comment]
Added links to developer material
