### ISSUE TITLE
failed to upload javascript

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#172]
Is there any way to combat this issue when saving changes to javascript files?

More often it uploads on the next attempt, but occasionally seems to get stuck not being able to upload for long periods of time

<img width="569" alt="screenshot 2015-09-27 18 22 43" src="https://cloud.githubusercontent.com/assets/7974754/10124117/c8c5acd4-6544-11e5-99a0-7d5eabeafe59.png">

Subjectively, it may resolve when making changes to another game's JS

There's not really any indication of when the server is ready to receive files or when it's busy

A progress bar / ring of death / sand timer would be helpful

Also a timeout for this error & the wait for connection error, as it's annoying to press the back button twice every time

**Comment by aliekiddo** [comment]
I've got 2 editor tabs open, one I can save, and the other it keeps failing - if it were a general connection issue, surely it cause problems for all uploads, not just in one case??

**Comment by ashcairo** [comment]
General fix going in with https://github.com/playir/playir/issues/195
