### ISSUE TITLE
Map Editor Model Render order / Backface problem

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#19]
1) Animated models in the Map Editor do not display correctly. They don't respect drawing order. As models rotate around the y axis polygons that should go to the back remain in front.

2) A byproduct of showing this bug: changing the selected model and then clicking the edit button (dashed outline square) still shows the old model till we click the map and back again.

Video 

http://youtu.be/FIcAcoLHeTU

**Comment by ashcairo** [comment]
2) That's a selection box, used to drag select multiple objects.

**Comment by drdavient** [comment]
Can we add some contextual response. Mouseover / touch hover text to help the user?

**Comment by ashcairo** [comment]
@drdavient yep, gamification for the editor is necessary, but this request should be listed as a separate enhancement issue.

**Comment by drdavient** [comment]
cool beans will do

Dave Cooper
¿â°Ø´óÎÀ

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
drdavient.co.uk
http://redpirates.org
