### ISSUE TITLE
Starting from scratch

### ISSUE THREAD

**Issue by ghost** [xcreatelabs/playir#193]
Hello everyone. I tryed to open a game template (please add blank template, as I'm forced to start from a template in the android app) and erasing all the contents.
I can see the UI elements I create, but I don't know how to use them to interact with the game.
Let's assume I have a UI with a start button, another with four buttons (for up, down, left and right) and I can, pressing on start, display the other UI or the level.
Let's also assume I have a small level, with a cube I wish to move around.
I would use the buttons for direction to move the cube, but I don't know how to do so.
Also, the buttons should appear as I load the level, but i can just open one or the other, not both.
Thanks in advance for any help.

**Comment by ashcairo** [comment]
@berserk82 Sounds great, I'll create a base template with what you specified now. Can you let me know your current app id, so I can get a better idea of what you've done so far?

**Comment by ghost** [comment]
where can I get it?

**Comment by ashcairo** [comment]
Should be in the publication tab

**Comment by ghost** [comment]
It's 117806

**Comment by ghost** [comment]
Note I didn't publish the app

**Comment by ghost** [comment]
Then?

**Comment by ashcairo** [comment]
Just looking into it now, will let you know once it's ready.

**Comment by ghost** [comment]
Ok thanks a lot

**Comment by ghost** [comment]
nothing yet? i discovered i can add javascript code in the browser based editor, but i can't on the android app. is this useful?

**Comment by ashcairo** [comment]
It's very useful if you're able to type in scripting. At the moment the visual scripting is still in development, so more advanced events require JavaScript. I took a look at your game, currently it's based on the Shooter example, which shows the start screen, then when you select Level 1 it enters into a level, which you can control your character using the controls on the left and right.

For the 3D cube example, are you looking for a more stripped down version of this. With the start screen being only one start button. And the level being a cube, with up/down/left/right controls rather than a circle?

**Comment by ghost** [comment]
I didn't fully get it.
Anyhow I would like to move my cube using the controls on gui 2.
How do I do?

**Comment by ashcairo** [comment]
I can't see gui2 in the app id you sent me. Did you create a new one, or are you wanting a template with one level scene featuring a cube, and one gui with a control d pad?

**Comment by ghost** [comment]
I created 2 guis.
1 with the start button and 1 with 4 boxes, which is meant to be the
controller
Il 15/Dic/2015 10:05, "ashcairo" notifications@github.com ha scritto:

**Comment by ashcairo** [comment]
Found them thanks!

**Comment by ashcairo** [comment]
Will give you an update once this is done on your app.

**Comment by ghost** [comment]
Any news?

**Comment by ashcairo** [comment]
Just updated your app, and added a new template called Cube Controls. Working on a guide to explain how it works.

In Level1, there's a cube with the name "player".

The Game.js file uses that to base your character from. So if you change the cube to another object, it'll use that for the player instead.

Controls are passed from the UIControls scene to Game.js, with both examples of an analogue and digital controls.

Please let me know how else I can help.

**Comment by ghost** [comment]
Thanks so much.
