### ISSUE TITLE
Custom Loading Screen Size

### ISSUE THREAD

**Issue by ashcairo** [xcreatelabs/playir#198]
There's also this one other bug.
I put in a custom loading screen (My logo) but when the game is loading the logo shows up fine but when the bar starts to get to the end the logo zooms in. If the same thing doesn't happen to you I can show pictures. I think it's supposed to happen, but at the same time not sure.

**Comment by ashcairo** [comment]
Fixed in next version (should be rolling out over the next few hours).

**Comment by CraftedCube** [comment]
Fixed on Playir but not safari.

**Comment by ashcairo** [comment]
From @CraftedCube - The loading screen bug was fixed on Playir, but not safari.

**Comment by CraftedCube** [comment]
Loading screen size is fine, it stays the same size on safari too.

**Comment by ashcairo** [comment]
@CraftedCube is it broken on Safari still then? Or working fine now?

**Comment by CraftedCube** [comment]
It's working on safari
