### ISSUE TITLE
Mobile Web: Add icon to Home Screen

### ISSUE THREAD

**Issue by ashcairo** [xcreatelabs/playir#199]
On IOS and Android when you add a website to your homescreen the icon is set by the website owner, but when the owner hasn't setup an icon, it'll turn out like a mini screenshot of the website or a random picture. I've designed an app icon for my game but it turns out there's no feature to put this icon in game. Here's some pictures.

![Uploading unnamed.png…]()

**Comment by ashcairo** [comment]
![unnamed 1](https://cloud.githubusercontent.com/assets/659599/14037778/b5c3ef1e-f23f-11e5-9794-4e25911d8a3c.png)

**Comment by ashcairo** [comment]
Just pushed out a fix, should be available shortly. @CraftedCube

![img_0049](https://cloud.githubusercontent.com/assets/659599/14047029/354eea6a-f29d-11e5-8730-63b4737c6cd3.PNG)

**Comment by CraftedCube** [comment]
That's awesome!

**Comment by CraftedCube** [comment]
The loading screen bug was fixed on Playir, but not safari.

**Comment by ashcairo** [comment]
From @CraftedCube
Okay, the icon was working. Now it's this.
![unnamed](https://cloud.githubusercontent.com/assets/659599/14100632/c80a996c-f586-11e5-8f89-73cb2c022c47.png)

**Comment by ashcairo** [comment]
@CraftedCube Can you let me know if it changed on it's own? If so at which point (after a reset or after an hour etc)?

**Comment by CraftedCube** [comment]
It happened literally 5 minutes after putting it on my homescreen, by itself.

**Comment by CraftedCube** [comment]
Still the same icon

**Comment by CraftedCube** [comment]
@ashcairo App icon seems to be working again

**Comment by CraftedCube** [comment]
@ashcairo Never mind, it shows the Playir logo again.

**Comment by ashcairo** [comment]
@CraftedCube can you give it a go now?

**Comment by CraftedCube** [comment]
It's working at the moment, I'll update you in a few hours if anything changes
(Few hours = Tonight)

**Comment by CraftedCube** [comment]
App icon is working 100% Thank You!
I really only need the major "game breaking" bugs fixed now. Like the black bar, messed up GUI on phones, and a new keyboard bug I found which I've posted on github. Then the little features and stuff can be added later.

Again no rush, I'm learning HTML5 and more things about Playir and stuff, so just take your time. :P
