### ISSUE TITLE
CraftWorlds Template - Safari Crash/Freeze while chatting.

### ISSUE THREAD

**Issue by CraftedCube** [xcreatelabs/playir#205]
CraftWorlds on safari crashes or freezes when pressing the white bar for the keyboard to show up. This happens every single time.

**Comment by CraftedCube** [comment]
@ashcairo

**Comment by ashcairo** [comment]
224010

**Comment by ashcairo** [comment]
@CraftedCube can you give it a try now? When you open the chat input, just tap on the white box and it should open up the keyboard.

**Comment by CraftedCube** [comment]
Fixed :)

**Comment by CraftedCube** [comment]
Have you figured out the phone GUI bug? That's my main worry at the moment.

**Comment by ashcairo** [comment]
Which issue do you mean by the GUI bug?

**Comment by ashcairo** [comment]
This one?
https://github.com/playir/playir/issues/200

**Comment by CraftedCube** [comment]
![image](https://cloud.githubusercontent.com/assets/13810269/14248966/78491c28-fa45-11e5-9356-c40977451fcd.jpeg)

This.

I've actually never had the D-pad bug ever happen again, so I assume that one is fixed.

**Comment by CraftedCube** [comment]
On phones the game is zoomed out too much, the GUI is squished in and out of place.
