### ISSUE TITLE
CraftWorlds Template - Black bar on bottom of screen

### ISSUE THREAD

**Issue by ashcairo** [xcreatelabs/playir#206]
@CraftedCube Can you let me know if it's still there now?

**Comment by CraftedCube** [comment]
still there.

**Comment by CraftedCube** [comment]
![image](https://cloud.githubusercontent.com/assets/13810269/14173588/c434b084-f70c-11e5-8cb4-0d0841b2f23d.png)

**Comment by ashcairo** [comment]
@craftedcube how about now?

http://playir.com/x/#id=224010

**Comment by CraftedCube** [comment]
Alrighty seems to be fixed!

Now the Phone GUI bug. Then you could possibly do the little enchantments I requested
:P

**Comment by CraftedCube** [comment]
Oh yeah and the keyboard chat safari bug is a big one too.

Then the little things that don't have to be done as soon as possible.

**Comment by CraftedCube** [comment]
@ashcairo
