### ISSUE TITLE
CraftWorlds Template - Phone GUI bug

### ISSUE THREAD

**Issue by CraftedCube** [xcreatelabs/playir#208]
![image](https://cloud.githubusercontent.com/assets/13810269/14249064/e07717dc-fa45-11e5-94f4-e5db39d71dd0.jpeg)

GUI is squished in and out of place, the game is also zoomed out too much.

**Comment by ashcairo** [comment]
@CraftedCube Is the bug that there's a black bar at the bottom of the screen?

**Comment by CraftedCube** [comment]
It's hard to explain unless you see it in person.

The black bar thing is fixed, this is just an old picture I took. The GUI for phones is pushed to the middle of the screen, the game is zoomed out, and text glitches out.

**Comment by ashcairo** [comment]
Can you post another photo of what it looks like, to get a better idea. The photo with the black bar makes it a little confusing.

**Comment by CraftedCube** [comment]
GUI bug is fixed
