### ISSUE TITLE
CraftWorlds Template - Projectile fires when tapping the chat button

### ISSUE THREAD

**Issue by CraftedCube** [xcreatelabs/playir#211]
A projectile fires when you hit the chat button, this happens everytime.

Just found these bugs after I made the game public.

**Comment by CraftedCube** [comment]
@ashcairo

**Comment by ashcairo** [comment]
@CraftedCube is this on the web or on a particular mobile device?

**Comment by CraftedCube** [comment]
@ashcairo Not sure, it happens on the fullscreen version, so it might be safari too.
But I know it happens on fullscreen

**Comment by CraftedCube** [comment]
Also I don't know if you planned on fixing more bugs, but I was wondering if you could give a quick tutorial on YouTube on how to add blocks into the shop and change the prices and stuff, also hoe to add characters to the menu. Then add the line of code in the description.

**Comment by ashcairo** [comment]
@CraftedCube  Can't reproduce this bug, let me know which device it occurs on, so I can help.

Will put the YouTube vid as a separate issue so I don't forget.
