### ISSUE TITLE
Support for FBX files with baked textures

### ISSUE THREAD

**Issue by ashcairo** [xcreatelabs/playir#217]

**Comment by ashcairo** [comment]
From Nick: "Hello, Here is the .fbx file. Hopefully you find a fix for it. (:"

**Comment by ashcairo** [comment]
Thanks for the file. Got it working! Will release the fix shortly.
![screen shot 2016-04-24 at 21 08 05](https://cloud.githubusercontent.com/assets/659599/14770091/d9346f80-0a60-11e6-9e9d-e3ae4168b744.jpg)

**Comment by Nick-izer** [comment]
Awesome!

**Comment by ashcairo** [comment]
Fix is live on the web and has been submitted to Apple and Android for approval. Should be in the app in a week.
