### ISSUE TITLE
Game assets seem to take forever (never) to load

### ISSUE THREAD

**Issue by ashcairo** [xcreatelabs/playir#3]
Map is missing, most models missing. Think it’s a network issue?

Tested on Android. User based in China.

**Comment by ashcairo** [comment]
Just pushed an update to inform the js thread of failed image downloads, and to retry downloading image 3 times before failing.

**Comment by drdavient** [comment]
Still occurring, I thought this was maybe less pronounced since update. However today I am having just as many issues. In WOF game only the skybox and health packs are appearing, all other models are white bounding boxes or planes.

**Comment by ashcairo** [comment]
@drdavient Can you try a fresh install of the Android client, and let me know if this issue still occurs?

**Comment by ashcairo** [comment]
Unable to reproduce.
