### ISSUE TITLE
All Multibased games hang at "Connecting"

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#30]
Tested on Samsung Galaxy S2 (i9100)
Cyanogenmod 10.1.3-i9100 
Android 4.2.2

All Multi based games hang with the "connecting".

**Comment by drdavient** [comment]
Was thinking of reflashing my phone to stock to fix but after the new update. (got today how can we see what the date of an update is?) Now its working for PLAYIR app, but the other "native" apps, that is those that boot directly do not connect.

**Comment by drdavient** [comment]
More details: Eg, on Phone wars, at the Character Select Screen the message at the bottom reads connecting and cannot go into a game

**Comment by ashcairo** [comment]
Unable to reproduce.
