### ISSUE TITLE
UIScenes - > Add Hangs

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#34]
1 Create New Game
2 Click UIScenes Add Button
3 Click any Closed (Red) or Open Source (Green) UI JS file.

The UI JS Button is depressed, but then sticks. The page hangs and will not respond.

**Comment by drdavient** [comment]
This is still an issue for me. Can we reopen?

**Comment by ashcairo** [comment]
Try force clearing your cache.
If it still hangs, check the JavaScript console and let me know what the error is.

To open the Console tab, do one of the following:
Use the keyboard shortcut Command - Option - J (Mac) or Control -Shift -J (Windows/Linux).
Select View > Developer > JavaScript Console.

**Comment by drdavient** [comment]
OK the force clear fixed things. Is that going to be necessary every time we update or can we get around that?

**Comment by ashcairo** [comment]
Add a new feature request.

On 11 November 2013 03:24, drdavient notifications@github.com wrote:

> OK the force clear fixed things. Is that going to be necessary every time
> we update or can we get around that?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/softwareispoetry/multi/issues/34#issuecomment-28171215
> .

## 

Ashraf Samy Hegab
http://playir.com
http://www.linkedin.com/profile/view?id=13244563

P.S. We're making some amazing open source games and revolutionary
real-time dev tools: http://igg.me/at/playir/x/3276321
