### ISSUE TITLE
Instant Update Failing in WOF Template

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#37]
I've built a WOF Template game (447 Unpublished).

Editing the title screen UI to move the logo around results in no change propagating to the game in play on either the web or android client. (Google Chrome, Samsung i9100)

see video : http://youtu.be/Q2-MW_8RWTU

**Comment by ashcairo** [comment]
Works fine here.
Try force cleaning your browser cache.

**Comment by drdavient** [comment]
Slapped myself that I didn't try this first... However, no joy. I'll fiddle
more later.

Dave

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org

**Comment by drdavient** [comment]
So it seems that (today at least) shift f5 wasn't successful in fixing the
problem. However ctrl-f5 did... Both should happily do a force refresh in
Chrome.

Is there a way to do the same force refresh in the Android client? That is
still not picking up the changes

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org

**Comment by ashcairo** [comment]
Android client already does a force refresh.

**Comment by drdavient** [comment]
Perhaps it does. But I still have the issue that the updates don't
propagate to my i9100 as per the video. Any thoughts?
(Browser version is definitely fixed by the Ctrl-F5)

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org

**Comment by ashcairo** [comment]
OK, will investigate on Android.

**Comment by ashcairo** [comment]
Fixed.

**Comment by drdavient** [comment]
What was the issue?

I'm still seeing the same problem. No updates on my Android. Do I nee to do
anything special to get the update? I'm assuming its applied automatically.

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org

**Comment by drdavient** [comment]
Not sure what changed, but now I am getting the updates. (I spotted that
all games in the game browser now have a white border so I tried again, and
now it works)

Dave Cooper
¿â°Ø´óÎÀ

http://www.kickstarter.com/projects/920406198/playir-drag-and-drop-3d-multiplayer-game-designer
Making multiplayer game design, and development easy!

Please support us on
indiegogohttp://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

http://www.indiegogo.com/projects/playir-open-source-games-real-time-design-tools

China +86 186 1176 4913
UK     +44  77  6156 4320
dave.e.cooper@gmail.com
http://drdavient.com
http://redpirates.org
