### ISSUE TITLE
[Feature Request] Simplify filenames on export.

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#40]
On export of Zip file, it would be nice to have all files stripped of their numeric id. Such that a file like helloui_87658765.js becomes simply helloui.js in the downloaded zip file. 

This will make editing offline much easier.

**Comment by ashcairo** [comment]
Now exports the filenames as their fileIDs, and on runtime writes out the token name it's expecting. So you can modify the files locally.

Next time you update the files on the server, it will use the server side version rather than the locally written version until re-export.
