### ISSUE TITLE
duplicate character is randomly created, 

### ISSUE THREAD

**Issue by foyzul-playir** [xcreatelabs/playir#44]
if you look at this screenshot below, that Windows Phone character that is standing in front of the iPhone character is a 'dummy'; is is were my original character was standing before suddenly creating a duplicate of itself. Now the Windows phone character that is playable is the bottom one that has its back facing us. That dummy can be attacked but cannot be killed. It does not move either.
- I noticed it happens when a 'connecting' messages appears on the side of the screen. Maybe cos I was playing and the game lost connection for a brief moment.

![image](https://cloud.githubusercontent.com/assets/7979998/3379285/1cdd051c-fbef-11e3-9d5a-5ae1f1f5f62a.png)

**Comment by ashcairo** [comment]
Thanks for the bug report, it's now fixed! So let me know if this issue comes up again.

Would be ace in future if you rotated the image before attaching to save me rotating my head :)
