### ISSUE TITLE
Rotate 3D models in the editor as well as scaling them

### ISSUE THREAD

**Issue by foyzul-playir** [xcreatelabs/playir#45]
A feature to rotate 3D models, as well as scaling them in the level editor. This adds more flexibility to users who import models that don't import the right way.

**Comment by ashcairo** [comment]
FBX and 3DS models can be rotated to correct bad imports, see the controls on the bottom right.

![screen shot 2014-06-25 at 22 51 33](https://cloud.githubusercontent.com/assets/659599/3392346/745b707a-fcb3-11e3-8d76-f9064d5705d8.jpg)
