### ISSUE TITLE
Editor: control camera view aside from the cube

### ISSUE THREAD

**Issue by foyzul-playir** [xcreatelabs/playir#46]
rather than just using the cube, hold down space bar and click inside editor to be able to rotate camera. Eg; hold space and click-drag mouse right to rotate camera/floor - Same function as the cube - but more familiar to users of photoshop and 3d software users I guess :)

![feature_rotate editor with space bar shortcut](https://cloud.githubusercontent.com/assets/7979998/3398505/b2d82d84-fd30-11e3-95c6-dae1d52dad9f.JPG)

**Comment by ashcairo** [comment]
Done :+1:

**Comment by foyzul-playir** [comment]
WHAT NO WAY, you done it already! 

Thanks, it makes editing and looking around the level much more efficient

Also noticed a cool tip: click the cube to return the camera back to top view of the map; don't know it that was there before but it's a nice touch
 
Foyzul.

.....................................
07877 430 673 
www.foyzulhassan.com

On Thursday, 26 June 2014, 17:22, ashcairo notifications@github.com wrote:

Closed #46.
