### ISSUE TITLE
changes do not save for 3d models in the editor? (Y value)

### ISSUE THREAD

**Issue by foyzul-playir** [xcreatelabs/playir#48]
After importing model onto stage and editing its position using the co ordinates, I exit the level but when i return the models' Y position does not save. It still ends up halfway between the stage.

What I did:
- I entered the model's Y coords as 12 and as 12.00 to see if it made a difference, no diffrence.
- I moved the 3D model around the stage, the X position saves when editor is closed and opened again.

![changes does not save](https://cloud.githubusercontent.com/assets/7979998/3398321/f9f41514-fd2d-11e3-8e26-e4cd1ab0b408.JPG)

![changes does not save 2](https://cloud.githubusercontent.com/assets/7979998/3398374/e91642f2-fd2e-11e3-80b3-cd104fc10f1a.JPG)

**Comment by ashcairo** [comment]
Ok, it's finally le fixed: https://twitter.com/playinrealtime/status/498645881571536896/photo/1

**Comment by foyzul-playir** [comment]
omg this is brilliant! Oh there was another bug or something that i forgot to report, not sure if you knew about it already: 
When you copy-paste models, pasting models makes them all jump from their current position to a another random position. I laid out some models nicely, copied them and when I hit paste, the duplicates were not lined up like the original, and the original models also moved place, which meant I had to reposition everything again
 
Foyzul.

.....................................
07877 430 673 
www.foyzulhassan.com

On Monday, 11 August 2014, 2:46, ashcairo notifications@github.com wrote:

Closed #48.

**Comment by ashcairo** [comment]
That should be fixed too.

Also, added in a shortcut key for raising the y position.
Mac = (Command+Up or Command+Down)
Windows = (Control+Up or Control+Down)
