### ISSUE TITLE
3d model not loading properly on iphone

### ISSUE THREAD

**Issue by foyzul-playir** [xcreatelabs/playir#49]
The 3d model I imported onto the stage still does not show on my phone;
- iPhone 5
- did a hard reset and soft reset to see if it makes a difference
- Maybe it takes while to load? Left the game running for a few minutes to see what happens.
- 3D model imported is too big?

![3d model not loading issue](https://cloud.githubusercontent.com/assets/7979998/3398482/51fd90f8-fd30-11e3-94e3-7c72aeafc1d4.PNG)

**Comment by ashcairo** [comment]
@foyzul-playir Can you let me know the app id of the game you're trying to load?

**Comment by foyzul-playir** [comment]
sorry forgot to include this:
App ID 639
 
Foyzul.

.....................................
07877 430 673 
www.foyzulhassan.com

On Thursday, 26 June 2014, 15:53, ashcairo notifications@github.com wrote:

Can you let me know the app id of the game you're trying to load?

**Comment by ashcairo** [comment]
@foyzul-playir Seems to load fine here, have you changed the asset that wasn't working since your issue report?

**Comment by foyzul-playir** [comment]
I'll try it again, I'll delete this model and import another version and see if it makes any difference.

Also I'll check whether I'm exporting the model properly to .3ds, maybe the uv map is not exporting with the model? I think I got some sort of message when I exported regarding the uv map but ignored it cos the model  I uploaded into the editor previewed it fine 

---

**Comment by ashcairo** [comment]
If you have any problems with importing a model, email me it and I'll test
it out here.

**Comment by foyzul-playir** [comment]
Have you figured out the other problem I was having where the Y position of my model doesn't seem to stay in the same position when I leave the editor? And ideas what I could be doing wrong?

---

**Comment by ashcairo** [comment]
Still working on it.

**Comment by foyzul-playir** [comment]
Got it sitting upright and aligned with the playfield:
imported a new version of the model, made sure to align it with the grid/floor inside 3DSMAX, then exported it as a FBX and uploaded.

So to conclude: reason for it being uploaded wrong way the first time is because of how I created it in 3DS max; I didn't align it with the stage

I'm sure you agree that being able to rotate the model inside the editor would be a great feature.

I have a few new feature requests which i will post on Github too :)
 
Foyzul.

.....................................
07877 430 673 
www.foyzulhassan.com

On Saturday, 28 June 2014, 10:30, ashcairo notifications@github.com wrote:

Still working on it.

**Comment by ashcairo** [comment]
Ok, cool, I'll close this ticket then as it seems to be working ok for you.
