### ISSUE TITLE
3D Models unsorted category: Test Failed error message

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#60]
When opening the unsorted menu this error message pops up

![screenshot 2014-08-08 20 54 01](https://cloud.githubusercontent.com/assets/7974754/3862012/017414cc-1f36-11e4-895e-3f8c14e17e75.png)

after pressing ok, the menu either re-appears instantly or doesn't go away but  checking the 'prevent further dialogues' box gets rid of it

![screenshot 2014-08-08 20 54 13](https://cloud.githubusercontent.com/assets/7974754/3862011/0173a5fa-1f36-11e4-926a-fbd92ed108b7.png)

The models in the unsorted category fails to load

![screenshot 2014-08-08 20 54 41](https://cloud.githubusercontent.com/assets/7974754/3862014/0175de60-1f36-11e4-846c-3e02a1aac95e.png)

When selecting any of these, processing appears & it stays this way on screen

![screenshot 2014-08-08 20 54 57](https://cloud.githubusercontent.com/assets/7974754/3862013/0175d442-1f36-11e4-858f-cc1eda1eb33e.png)

Browser : Firefox 31
OSX Mavericks

**Comment by ashcairo** [comment]
Fixed. Try force refreshing. (Command+Shift+R)

**Comment by aliekiddo** [comment]
Yep, fixed
