### ISSUE TITLE
3D Models don't always show when dropped in for the 1st time

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#64]
Over the weekend, I've had some issues when dropping in a new model & texture, it's been uploading & processing, but nothing appears.  If I drop it in a 2nd time, it uploads & processes as normal, sometimes the texture has been missing

![screenshot 2014-08-11 16 52 12](https://cloud.githubusercontent.com/assets/7974754/3878547/0cb9b8fa-2170-11e4-8ba2-530311d4d3e4.png)

I tried some more tests earlier today, & it's happened a few more times, but not as often

Although it could be subjective, dropping in seems more reliable from Windows Explorer than OSX Finder

**Comment by ashcairo** [comment]
Could you email me the models & textures you're trying to use? (ash@playir.com)

**Comment by ashcairo** [comment]
Fixed
