### ISSUE TITLE
Feature request: camera rotation snap

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#67]
In the 3D model editor, a way to snap camera rotation to 90º - front, back, left side, right side, top, bottom...  maybe by holding shift whilst dragging - like in ZBrush - perhaps 2 finger dragging on mobile devices

**Comment by ashcairo** [comment]
![output_xdhjlt](https://cloud.githubusercontent.com/assets/659599/3899986/9823275a-2283-11e4-80c3-17afadcb517e.gif)
Added the rotation cube from the level editor for consistency, to snap to closest side.
