### ISSUE TITLE
Textures don't always appear

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#73]
Textures don't always appear first time when dragging in a model with a texture

**Comment by ashcairo** [comment]
Thanks for the report. Should be now fixed.

**Comment by aliekiddo** [comment]
I'm still getting it

**Comment by ashcairo** [comment]
Try to force refresh your browser cache.

**Comment by aliekiddo** [comment]
Have done, cleared cookies & cache
3 browsers - Firefox, Chrome & Opera

**Comment by ashcairo** [comment]
The server has a 4 hour cache time per user. Try again in 4 hours.

**Comment by aliekiddo** [comment]
Yep, it seems good now

**Comment by ashcairo** [comment]
Thanks Alex!
