### ISSUE TITLE
Blank bar at the bottom of screen whilst in gameplay

### ISSUE THREAD

**Issue by aliekiddo** [xcreatelabs/playir#86]
![screenshot_2014-11-12-17-28-29](https://cloud.githubusercontent.com/assets/7974754/5059515/1058124e-6d16-11e4-97c5-e8a67dc9336a.png)
![screenshot_2014-11-15-22-10-35](https://cloud.githubusercontent.com/assets/7974754/5059519/2d563db2-6d16-11e4-9467-2a315923b9aa.png)
It isn't there in the app select or start UI's of the games.
I've tested on 2 android devices ICS & Kitkat

**Comment by ashcairo** [comment]
Disable adblock plus.

**Comment by aliekiddo** [comment]
Ah I see, it didn't behave in this way on previous versions
