### ISSUE TITLE
Food Fighters Start Screen Characters Don't Appear

### ISSUE THREAD

**Issue by drdavient** [xcreatelabs/playir#9]
Load Food Fighters. No  Character Sprites appear on the Start screen either side of the VS.

This may be a network issue? But a reinstall, and retry gives same result on Android, based in Beijing.

![2013-08-17 21 08 43](https://f.cloud.github.com/assets/4351544/981045/3b703c3e-073e-11e3-9e0c-a6b4358af61c.png)

**Comment by ashcairo** [comment]
Same underlying issue as reported: https://github.com/softwareispoetry/multi/issues/3
